export const SIGN_UP='SIGN_UP'
export const SIGN_IN='SIGN_IN'
export const SIGN_OUT='SIGN_OUT'
export const FORGOT_PASS='FORGOT_PASS'
export const RESET_PASS='RESET_PASS'
export const UPDATE_CURRENT_USER='UPDATE_CURRENT_USER'
export const UPDATE_CURRENT_USER_PASS='UPDATE_CURRENT_USER_PASS'
export const GET_CURRENT_USER='GET_CURRENT_USER'

export const FETCH_FACILITES='FETCH_FACILITES'
export const FETCH_FACILITY='FETCH_FACILITY'
export const FETCH_FACILITY_STATS='FETCH_FACILITY_STATS'

